# Generated by Django 6.0 on 2026-01-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер потягу')),
                ('travel_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Час у дорозі')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='cities.city', verbose_name='З якого міста')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='cities.city', verbose_name='До якого міста')),
            ],
            options={
                'verbose_name': 'Потяг',
                'verbose_name_plural': 'Потяги',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TrainTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер потягу')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city', verbose_name='З якого міста')),
            ],
        ),
    ]
