# Generated by Django 6.0 on 2026-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_traintest_from_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='travel_time1',
            field=models.DurationField(blank=True, null=True, verbose_name='Час у дорозі'),
        ),
    ]
