# Generated by Django 6.0 on 2026-01-24 17:49
from datetime import timedelta

from django.db import migrations

def fill_table(apps, schema_editor):

    db_alias = schema_editor.connection.alias
    Train = apps.get_model('trains', 'Train')
    qs = Train.objects.using(db_alias).all()
    for q in qs:
        travel_time = q.travel_time # 'Це децимал
        hours = int(travel_time) # забираємо цілу частину (години)
        minutes = int(60 * (travel_time - hours)) # формуємо хвилини
        q.travel_time1 = timedelta(days=0, hours=hours, minutes=minutes)
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_train_travel_time1'),
    ]

    operations = [
        migrations.RunPython(fill_table),
    ]
