# Generated by Django 6.0 on 2026-01-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_auto_20260124_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='travel_time',
        ),
    ]
