# Generated by Django 6.0 on 2026-01-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0005_remove_train_travel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='travel_time1',
            new_name='travel_time',
        ),
    ]
