# Generated by Django 6.0 on 2026-01-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_alter_city_options'),
        ('trains', '0002_alter_traintest_from_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Назва маршруту')),
                ('total_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Час у дорозі')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_route', to='cities.city', verbose_name='З якого міста')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_route', to='cities.city', verbose_name='До якого міста')),
                ('trains', models.ManyToManyField(to='trains.train', verbose_name='Список поїздів')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['name'],
            },
        ),
    ]
