# Generated by Django 6.0 on 2026-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='total_time',
            field=models.DurationField(verbose_name='Час у дорозі'),
        ),
    ]
